### PR TITLE
Dashboard, chat and channels files - raw

### PR DESCRIPTION
**Pull request by Mirai500**
These are the raw files for the dashboard, chat and channel components. Here is what i envision: Once a user logs in, they are taken to another login page here they decide if they want to create a room or join a room. If they create a room, a unique ID is generated which anyone seeking to access the room requires to join. This will ensure privacy of doctors DM's and channels. The files are still being worked on. Ignore the scss files and create css files for the pages. I haven't installed the dependencies on the branch so you may do so from your end.

### CODE REVIEW

**Comment by R-Owino** [comment]
How about after login, they get directed to a dashboard with all options (avoid double log in) so they can choose if they want to join a room - which will require approval from the room creator/admin or create a room. What do you think?

**Comment by Mirai500** [comment]
Okay. That should work. Let me work on that.

**Comment by R-Owino** [comment]
Okay. UUID can work too

**Comment by Mirai500** [comment]
dashboard
Something like this should work. Haven't worked on the styling.

**Comment by R-Owino** [comment]
In this case, what token is the user supposed to enter? Where are they getting the token from?

**Comment by Mirai500** [comment]
I did some research on this. The I'd should be generated from the backend on button click. Then it would be sent/displayed in the chat room created. Thus the user can then share with whoever they want. That'll make it easier to handle the verification also.

**Comment by Mirai500** [comment]
Also, I may need to revert the merge. I'm trying to come up with something simpler that doesn't require as much files. To ease navigation and understanding.

**Comment by R-Owino** [comment]
I have created a PR to revert the changes and requested you to review

**Pull request merged**
