### PR TITLE
login rerouting

### PR DESCRIPTION
**Pull request by Kennedy826**
I have made changes to the login.js so if a user logs in successfully s/he will be directed to the dashboard page.

### CODE REVIEW

**Comment by doni-robert** [comment]
Why are node_modules being tracked? Shouldn't they be ignored?

**Comment by Kennedy826** [comment]
I realized that problem as well. I'm checking that.

**Review by doni-robert — COMMENTED** [review]
Thanks for the prompt changes

**Review by doni-robert — APPROVED** [review]
:+1:

**Pull request merged**
